### ISSUE TITLE
Pimcore 5.8.4 incompatibility

### ISSUE THREAD

**Issue by galum** [dachcom-digital/pimcore-members#100]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no

In a project which was using Members Bundle 2.3 I ran a Pimcore Composer Update to Pimcore 5.8.4 and Members 2.4.0 and the following error appeared (When clicking the Update "+" button in "Manage Extension" view in Backend). 

Message: Type error: Too few arguments to function MembersBundle\CoreExtension\Provider\RoleOptionsProvider::__construct(), 0 passed in /vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php on line 45 and exactly 1 expected

```
Status: 500 | Internal Server Error
URL: /admin/extensionmanager/admin/update
Method: POST
Message: Type error: Too few arguments to function MembersBundle\CoreExtension\Provider\RoleOptionsProvider::__construct(), 0 passed in /vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php on line 45 and exactly 1 expected
Trace: 
#0 /vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php(45): MembersBundle\CoreExtension\Provider\RoleOptionsProvider->__construct()
#1 /vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Multiselect.php(509): Pimcore\Model\DataObject\ClassDefinition\Helper\OptionsProviderResolver::resolveProvider('MembersBundle\\C...', 2)
#2 /vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(822): Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect->enrichFieldDefinition(Array)
#3 /vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(810): Pimcore\Model\DataObject\ClassDefinition->doEnrichFieldDefinition(Object(Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect), Array)
#4 /vendor/dachcom-digital/members/src/MembersBundle/Migrations/Version20190508092938.php(36): Pimcore\Model\DataObject\ClassDefinition->getFieldDefinitions()
#5 /vendor/pimcore/pimcore/lib/Migrations/Version.php(312): MembersBundle\Migrations\Version20190508092938->up(Object(ProxyManagerGeneratedProxy\__PM__\Doctrine\DBAL\Schema\Schema\Generated93cb4e52be36d1a0ab1c551957e06e24))
#6 /vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(172): Pimcore\Migrations\Version->execute('up', false, false)
#7 /vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/MigrationInstaller.php(311): Doctrine\DBAL\Migrations\Migration->migrate('20190508092938', false)
#8 /vendor/pimcore/pimcore/lib/Extension/Bundle/Installer/MigrationInstaller.php(254): Pimcore\Extension\Bundle\Installer\MigrationInstaller->migrateToVersion('20190508092938')
#9 /vendor/pimcore/pimcore/lib/Extension/Bundle/PimcoreBundleManager.php(614): Pimcore\Extension\Bundle\Installer\MigrationInstaller->update()
#10 /vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php(286): Pimcore\Extension\Bundle\PimcoreBundleManager->update(Object(MembersBundle\MembersBundle))
#11 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->updateAction(Object(Symfony\Component\HttpFoundation\Request))
#12 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#13 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#15 {main}
```

**Comment by solverat** [comment]
Hey @galum, please checkout this conversion: https://github.com/dachcom-digital/pimcore-members/issues/98

**Comment by galum** [comment]
Hello @solverat , thank you so much, and apologies that I did not notice the existing issue. Adding the  "@" at the beginning of class name for option provider of MembersGroups->roles field seems to fix the issue.
